### PR TITLE
Update client for multiple test

### PR DESCRIPTION
**Pull request by fordream910**

### CODE REVIEW

**Comment by jg33** [comment]
Don't have time to test it, just going to merge it.

**Comment by jg33** [comment]
Merging this one, too!

**Comment by Sheavideo** [comment]
Cool.
I'm trolling the Vuforia forums - putting a bunch of links on the hackpad.
L.

**Comment by jg33** [comment]
Awesome!

~~~Jesse Garrison

c: 347.267.7638

On Wed, May 27, 2015 at 1:22 PM, Sheavideo notifications@github.com
wrote:

> Cool.
> I'm trolling the Vuforia forums - putting a bunch of links on the hackpad.
> L.
> On 5/27/15 1:20 PM, Jesse Garrison wrote:
> 
> > Merged #1 https://github.com/jg33/ozUnity/pull/1.
> > 
> > —
> > Reply to this email directly or view it on GitHub 
> > https://github.com/jg33/ozUnity/pull/1#event-315153838.
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/jg33/ozUnity/pull/1#issuecomment-106003170

**Pull request merged**
